#server.port=4001
#spring.application.name=service-provider
#
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

server:
  port: 5001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8488
  application:
    name: SERVER-SHOP #此实例注册到eureka服务端的name