server:
  port: 6001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8488
  application:
    name: SERVER-GOODS
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

