server:
  port: 8000
#spring:
#  application:
#    name: admin


spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 5000
  application:
    name: service-gateway #此实例注册到eureka服务端的name
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://SERVER-USER
          predicates:
            - Path=/user/**,/userAddress/**,/userCollect/**,/userComment/**
        - id: admin
          uri: lb://SERVER-ADMIN
          predicates:
            - Path=/admin/**,/menu/**
        - id: product
          uri: lb://SERVER-PRODUCT
          predicates:
            - Path=/product/**
        - id: shop
          uri: lb://SERVER-SHOP
          predicates:
            - Path=/shop/**,/shopMenu/**,/shopAptitude/**,/shopUser/**
        - id: order
          uri: lb://SERVER-ORDER
          predicates:
            - Path=/orders/**,/orderGoods/**
        - id: order
          uri: lb://SERVER-GOODS
          predicates:
            - Path=/category/**,/goods/**,/goodsAttribute/**,/goodsSpecification/**,/upload/shop/**,/groupRoll/**,/groupRollDetail/**
#            - Query=name,1
#            - Query=age
#
#          filters:
#            - name: Hystrix
#              args:
#                name: fallbackcmd
#                fallbackUri: forward:/fallback
#            - name: RequestRateLimiter
#              KeyResolver: userKey
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 2


#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000
#      circuitBreaker:
#        requestVolumeThreshold: 5
#        sleepWindowInMilliseconds : 5000   时间